kind: Deployment
apiVersion: apps/v1
metadata:
   name: harshbhatt12
spec:
   replicas: 2
   selector:
    matchLabels:
     app: harshbhatt12
   template:
      metadata:
        labels:
          app: harshbhatt12
      spec:
       containers:
        - name: harshbhatt12
          image: harshbhatt12/containerized-application
          imagePullPolicy: Always
          ports:
          - containerPort: 80