kind: Service                             
apiVersion: v1
metadata:
  name: harshbhatt12
  labels:
    app: harshbhatt12
spec:
  ports:
    - port: 8090                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: harshbhatt12                    
  type: LoadBalancer                   
